services:
    kami_stock.watcher:
        class: Kami\StockBundle\Watcher\Watcher
        arguments:
          - '@kami_stock.binance.assets.watcher'
          - '@kami_stock.bitfinex.watcher'
          - '@kami_stock.poloniex.watcher'
          - '@kami_stock.coin_market.assets.watcher'
          - '@kami_stock.bittrex.assets.watcher'
        public: true

    kami_stock.volumes.watcher:
        class: Kami\StockBundle\Watcher\VolumesWatcher
        arguments:
          - '@kami_stock.binance.volumes.watcher'
          - '@kami_stock.bitfinex.volume.watcher'
          - '@kami_stock.poloniex.volume.watcher'
          - '@kami_stock.bittrex.volumes.watcher'
          - '@doctrine.orm.entity_manager'
          - '@snc_redis.default'
          - '@m6web_cassandra.client.default'
          - '@kami_stock.changes_helper'
          - '@lopi_pusher.pusher'
          - '@logger'
        public: true

    kami_stock.abstract.watcher:
        abstract: true
        arguments:
            - '@m6web_cassandra.client.default'
            - '@doctrine.orm.entity_manager'
            - '@logger'
            - '%proxy_url%'

    kami_stock.abstract.volumes.watcher:
            abstract: true
            arguments:
                - '@doctrine.orm.entity_manager'
                - '@logger'
                - '@snc_redis.default'
                - '%proxy_url%'

    kami_stock.bitfinex.watcher:
        class: Kami\StockBundle\Watcher\Bitfinex\BitfinexWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.bitfinex.volume.watcher:
        class: Kami\StockBundle\Watcher\Bitfinex\BitfinexVolumeWatcher
        parent: kami_stock.abstract.volumes.watcher

    kami_stock.poloniex.watcher:
        class: Kami\StockBundle\Watcher\Poloniex\PoloniexWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.poloniex.volume.watcher:
        class: Kami\StockBundle\Watcher\Poloniex\PoloniexVolumeWatcher
        parent: kami_stock.abstract.volumes.watcher

    kami_stock.coin_market.watcher:
        class: Kami\StockBundle\Watcher\CoinMarketCap\CoinMarketCapWatcher
        arguments:
            - '@doctrine.orm.entity_manager'

    kami_stock.coin_market.assets.watcher:
        class: Kami\StockBundle\Watcher\CCXT\CoinMarketCap\CoinMarketCapAssetsWatcher
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'

    kami_stock.changes_helper:
        class: Kami\StockBundle\ChangesHelper\ChangesHelper
        arguments:
            - '@m6web_cassandra.client.default'

    kami_stock.bittrex.assets.watcher:
            class: Kami\StockBundle\Watcher\CCXT\Bittrex\BittrexAssetsWatcher
            parent: kami_stock.abstract.watcher

    kami_stock.bittrex.volumes.watcher:
            class: Kami\StockBundle\Watcher\CCXT\Bittrex\BittrexVolumesWatcher
            parent: kami_stock.abstract.volumes.watcher

    kami_stock.binance.assets.watcher:
                class: Kami\StockBundle\Watcher\CCXT\Binance\BinanceAssetsWatcher
                parent: kami_stock.abstract.watcher

    kami_stock.binance.volumes.watcher:
                class: Kami\StockBundle\Watcher\CCXT\Binance\BinanceVolumesWatcher
                parent: kami_stock.abstract.volumes.watcher

    kami_stock.bitfinex.assets.watcher:
                class: Kami\StockBundle\Watcher\CCXT\Bitfinex\BitfinexAssetsWatcher
                parent: kami_stock.abstract.watcher

    kami_stock.bitfinex.volumes.watcher:
                class: Kami\StockBundle\Watcher\CCXT\Bitfinex\BitfinexVolumesWatcher
                parent: kami_stock.abstract.volumes.watcher

    kami_stock.poloniex.assets.watcher:
                    class: Kami\StockBundle\Watcher\CCXT\Poloniex\PoloniexAssetsWatcher
                    parent: kami_stock.abstract.watcher