services:
    kami_stock.watcher:
        class: Kami\StockBundle\Watcher\Watcher
        arguments:
          - '@kami_stock.binance.watcher'
          - '@kami_stock.bitfinex.watcher'
          - '@kami_stock.bittrex.watcher'
          - '@kami_stock.poloniex.watcher'
        public: true

    kami_stock.abstract.watcher:
        abstract: true
        arguments:
            - '@m6web_cassandra.client.default'
            - '@doctrine.orm.entity_manager'
            - '@logger'
            - '%proxy_url%'

    kami_stock.binance.watcher:
        class: Kami\StockBundle\Watcher\Binance\BinanceWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.bitfinex.watcher:
        class: Kami\StockBundle\Watcher\Bitfinex\BitfinexWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.bittrex.watcher:
        class: Kami\StockBundle\Watcher\Bittrex\BittrexWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.poloniex.watcher:
         class: Kami\StockBundle\Watcher\Poloniex\PoloniexWatcher
         parent: kami_stock.abstract.watcher