services:
    kami_stock.watcher:
        class: Kami\StockBundle\Watcher\Watcher
        arguments:
          - '@kami_stock.binance.watcher'
          - '@kami_stock.bitfinex.watcher'
          - '@kami_stock.bittrex.watcher'
          - '@kami_stock.poloniex.watcher'
          - '@kami_stock.coin_market.watcher'
        public: true

    kami_stock.volumes.watcher:
        class: Kami\StockBundle\Watcher\VolumesWatcher
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@snc_redis.default'
          - '@m6web_cassandra.client.default'
        public: true

    kami_stock.abstract.watcher:
        abstract: true
        arguments:
          - '@m6web_cassandra.client.default'
          - '@doctrine.orm.entity_manager'
          - '@logger'
          - '%proxy_url%'

    kami_stock.abstract.volumes.watcher:
        abstract: true
        arguments:
          - '@doctrine.orm.entity_manager'
          - '@logger'
          - '@kami_stock.bittrex.client'
          - '@snc_redis.default'
          - '%proxy_url%'

    kami_stock.binance.watcher:
        class: Kami\StockBundle\Watcher\Binance\BinanceWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.binance.volume.watcher:
        class: Kami\StockBundle\Watcher\Binance\BinanceVolumeWatcher
        parent: kami_stock.abstract.volumes.watcher

    kami_stock.bitfinex.watcher:
        class: Kami\StockBundle\Watcher\Bitfinex\BitfinexWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.bitfinex.volume.watcher:
        class: Kami\StockBundle\Watcher\Bitfinex\BitfinexVolumeWatcher
        parent: kami_stock.abstract.volumes.watcher

    kami_stock.bittrex.watcher:
        class: Kami\StockBundle\Watcher\Bittrex\BittrexWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.poloniex.watcher:
        class: Kami\StockBundle\Watcher\Poloniex\PoloniexWatcher
        parent: kami_stock.abstract.watcher

    kami_stock.poloniex.volume.watcher:
        class: Kami\StockBundle\Watcher\Poloniex\PoloniexVolumeWatcher
        parent: kami_stock.abstract.volumes.watcher

    kami_stock.bittrex.volume.watcher:
        class: Kami\StockBundle\Watcher\Bittrex\BittrexVolumeWatcher
        parent: kami_stock.abstract.volumes.watcher

    kami_stock.bittrex.client:
        class: Kami\StockBundle\Watcher\Bittrex\Utils\BittrexClient

    kami_stock.coin_market.watcher:
        class: Kami\StockBundle\Watcher\CoinMarketCap\CoinMarketCapWatcher
        arguments:
            - '@doctrine.orm.entity_manager'
            - '@logger'