services:
    kami.sync_assets.command:
        class: Kami\AssetBundle\Command\SyncAssetsCommand
        arguments:
            - "@kami_stock.watcher"
            - "@lopi_pusher.pusher"
        tags:
            - { name: 'console.command' }

    kami.sync_assets.volumes.command:
        class: Kami\AssetBundle\Command\SyncAssetsVolumesCommand
        arguments:
            - "@kami_stock.volumes.watcher"
        tags:
            - { name: 'console.command' }

    kami.sync_assets.historical_volumes.command:
        class: Kami\AssetBundle\Command\SyncHistoryVolumesCommand
        arguments:
            - "@kami_stock.history_volumes.watcher"
        tags:
            - { name: 'console.command' }

    kami.sync_assets.prices.command:
            class: Kami\AssetBundle\Command\SyncAssetsPricesCommand
            arguments:
                - "@doctrine.orm.entity_manager"
                - "@m6web_cassandra.client.default"
            tags:
                - { name: 'console.command' }