parameters:
    kami.token_screener.index_strategy:
        - get_asset_step
        - validate_resource_access
        - get_query_builder
        - build_select_query
        - sort
        - paginate
        - fill_tradeble_token_step
        - build_serializer
        - serialize
    kami.token_screener.filter_strategy:
        - get_asset_step
        - validate_resource_access
        - validate_filters
        - get_query_builder
        - build_select_query
        - filter_token_step
        - sort
        - paginate
        - build_serializer
        - serialize

services:
    kami.request_processor.fill_tradeble_token_step.step:
        class: Kami\AssetBundle\RequestProcessor\Step\FillTradebleTokenStep
        arguments:
            - "@m6web_cassandra.client.default"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "fill_tradeble_token_step" }
    kami.request_processor.get_asset_step.step:
        class: Kami\AssetBundle\RequestProcessor\Step\GetAssetReflectionFromRequestStep
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "get_asset_step" }
    kami.request_processor.filter_token_step.step:
        class: Kami\AssetBundle\RequestProcessor\Step\FilterTradebleTokenStep
        arguments:
            - "@kami.api_core.access_manager"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "filter_token_step" }

    kami.sync_assets.command:
        class: Kami\AssetBundle\Command\SyncAssetsCommand
        arguments:
            - "@kami_stock.watcher"
            - "@lopi_pusher.pusher"
        tags:
            - { name: 'console.command' }

    kami.sync_assets.volumes.command:
            class: Kami\AssetBundle\Command\SyncAssetsVolumesCommand
            arguments:
                - "@kami_stock.volumes.watcher"
            tags:
                - { name: 'console.command' }

    kami.sync.market_cap.command:
                class: Kami\AssetBundle\Command\SyncMarketCapCommand
                arguments:
                    - "@kami_stock.coin_market.watcher"
                tags:
                    - { name: 'console.command' }


