services:
    kami.sync_assets.command:
        class: Kami\AssetBundle\Command\SyncAssetsCommand
        arguments:
            - "@kami_stock.watcher"
        tags:
            - { name: 'console.command' }


