parameters:
    kami.token_screener.index_strategy:
        - get_asset_step
        - validate_resource_access
        - get_query_builder
        - token_build_select_query
        - sort_token
        - paginate
        - fill_tradeble_token_step
        - build_serializer
        - serialize
    kami.token_screener.filter_strategy:
        - get_asset_step
        - validate_resource_access
        - validate_filters
        - get_query_builder
        - token_build_select_query
        - filter_token_step
        - sort_token
        - paginate
        - fill_tradeble_token_step
        - build_serializer
        - serialize

services:
    kami.request_processor.fill_tradeble_token_step.step:
        class: Kami\AssetBundle\RequestProcessor\Step\FillTradebleTokenStep
        arguments:
            - "@snc_redis.default"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "fill_tradeble_token_step" }
    kami.request_processor.sort_token.step:
        class: Kami\AssetBundle\RequestProcessor\Step\SortStep
        arguments:
            - "@kami.api_core.access_manager"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "sort_token" }
    kami.request_processor.token_build_select_query.step:
        class: Kami\AssetBundle\RequestProcessor\Step\TokenBuildSelectQueryStep
        arguments:
            - "@kami.api_core.access_manager"
            - "@annotation_reader"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "token_build_select_query" }
    kami.request_processor.get_asset_step.step:
        class: Kami\AssetBundle\RequestProcessor\Step\GetAssetReflectionFromRequestStep
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "get_asset_step" }
    kami.request_processor.filter_token_step.step:
        class: Kami\AssetBundle\RequestProcessor\Step\FilterTradebleTokenStep
        arguments:
            - "@kami.api_core.access_manager"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "filter_token_step" }

    kami.sync_assets.command:
        class: Kami\AssetBundle\Command\SyncAssetsCommand
        arguments:
            - "@kami_stock.watcher"
            - "@lopi_pusher.pusher"
        tags:
            - { name: 'console.command' }

    kami.sync_assets.volumes.command:
        class: Kami\AssetBundle\Command\SyncAssetsVolumesCommand
        arguments:
            - "@kami_stock.volumes.watcher"
        tags:
            - { name: 'console.command' }

    kami.sync_assets.historical_volumes.command:
            class: Kami\AssetBundle\Command\SyncHistoryVolumesCommand
            arguments:
                - "@kami_stock.history_volumes.watcher"
            tags:
                - { name: 'console.command' }

