<?php

namespace Kami\FacebookParserBundle\Repository;

/**
 * FacebookUserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookUserRepository extends \Doctrine\ORM\EntityRepository
{
}
