cache:
  paths:
  - vendor/

variables:
    COMPOSER_DISABLE_XDEBUG_WARN: "1"
    COMPOSER_ALLOW_SUPERUSER: "1"

test:app:
    script:
        - composer install --prefer-dist --no-interaction --no-progress
        - ./vendor/bin/phpunit --coverage-text --colors=never