imports:
    - { resource: config.yml }

doctrine:
    orm:
        metadata_cache_driver: predis
        result_cache_driver: predis
        query_cache_driver: predis
    dbal:
        driver: pdo_pgsql
        url: "%env(DATABASE_URL)%"

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
