imports:
    - { resource: config.yml }
parameters:
    proxy_url: "%env(QUOTAGUARDSTATIC_URL)%"

doctrine:
    dbal:
        driver: pdo_pgsql
        url: "%env(DATABASE_URL)%"
    orm:
        metadata_cache_driver:
            id: snc.redis.doctrine.metadata_cache
        result_cache_driver:
            id: snc.redis.doctrine.result_cache
        query_cache_driver:
            id: snc.redis.doctrine.metadata_cache


snc_redis:
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default_entity_manager
        result_cache:
            client: cache
            entity_manager: default_entity_manager
        query_cache:
            client: cache
            entity_manager: default_entity_manager
        second_level_cache:
            client: default
            entity_manager: default
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false

m6web_cassandra:
    clients:
        default:
            contact_endpoints: [34.247.150.247, 34.254.25.212, 34.247.192.31]
            credentials:
                username: "%env(IC_USER)%"
                password: "%env(IC_PASSWORD)%"

# Kami IcoBench Configuration
kami_ico_bench:
    private_key: "%env(ICOBENCH_PRIVATE_KEY)%"
    public_key: "%env(ICOBENCH_PUBLIC_KEY)%"
    guzzle_options:
        proxy: "%env(QUOTAGUARDSTATIC_URL)%"

lopi_pusher:
    scheme: https
    host: api-eu.pusher.com
    port: 443
    cluster: eu
    timeout: 30
    debug: true
    app_id: 513696
    key: 139ee335d6ffa4609ca9
    secret: 4eb1eacb7beb23571c99