imports:
    - { resource: config.yml }

doctrine:
    dbal:
        driver: pdo_pgsql
        url: "%env(DATABASE_URL)%"

snc_redis:
    clients:
        default:
            type: predis
            alias: default
            dsn: "%env(REDIS_URL)%"
            logging: false
        cache:
            type: predis
            alias: cache
            dsn: "%env(REDIS_URL)%"
            logging: false
    doctrine:
        metadata_cache:
            client: cache
            entity_manager: default_entity_manager
        result_cache:
            client: cache
            entity_manager: default_entity_manager
        query_cache:
            client: cache
            entity_manager: default_entity_manager
        second_level_cache:
            client: default
            entity_manager: default
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false

m6web_cassandra:
    clients:
        default:
            contact_endpoints: "%env(IC_CONTACT_POINTS)%"
            credentials:
                username: "%env(IC_USER)%"
                password: "%env(IC_PASSWORD)%"

# Kami IcoBench Configuration
kami_ico_bench:
    private_key: "%ico_bench_private_key%"
    public_key: "%ico_bench_public_key%"
    guzzle_options:
        proxy: http://vw520rzfhacf1p:5eQVQyie4_ILLX_YOtlsvDqmCw@eu-west-static-01.quotaguard.com:9293