imports:
    - { resource: parameters.yml }
    - { resource: security.yml }
    - { resource: rest_resources.yml }
    - { resource: jwt.yml }
    - { resource: "@KamiContentBundle/Resources/config/services.yml" }
    - { resource: "@KamiWorkerBundle/Resources/config/services.yml" }

# Put parameters here that don't need to change on each machine where the app is deployed
# https://symfony.com/doc/current/best_practices/configuration.html#application-related-configuration
parameters:
    locale: en

framework:
    #esi: ~
    translator: { fallbacks: ['%locale%'] }
    secret: '%secret%'
    router:
        resource: '%kernel.project_dir%/app/config/routing.yml'
        strict_requirements: ~
    form: ~
    csrf_protection: ~
    validation: { enable_annotations: true }
    #serializer: { enable_annotations: true }
    default_locale: '%locale%'
    trusted_hosts: ~
    session:
        # https://symfony.com/doc/current/reference/configuration/framework.html#handler-id
        handler_id: session.handler.native_file
        save_path: '%kernel.project_dir%/var/sessions/%kernel.environment%'
    fragments: ~
    http_method_override: true
    assets: ~
    php_errors:
        log: true

# Twig Configuration
twig:
    debug: '%kernel.debug%'
    strict_variables: '%kernel.debug%'

# Doctrine Configuration
doctrine:
    dbal:
        driver: '%driver%'
        host: '%database_host%'
        port: '%database_port%'
        dbname: '%database_name%'
        user: '%database_user%'
        password: '%database_password%'
        charset: UTF8
        # if using pdo_sqlite as your database driver:
        #   1. add the path in parameters.yml
        #     e.g. database_path: '%kernel.project_dir%/var/data/data.sqlite'
        #   2. Uncomment database_path in parameters.yml.dist
        #   3. Uncomment next line:
        #path: '%database_path%'

    orm:
        auto_generate_proxy_classes: '%kernel.debug%'
        naming_strategy: doctrine.orm.naming_strategy.underscore
        auto_mapping: true

# Swiftmailer Configuration
swiftmailer:
    transport: '%mailer_transport%'
    host: '%mailer_host%'
    username: '%mailer_user%'
    password: '%mailer_password%'
    spool: { type: memory }

# FOSUser Configuration
fos_user:
    db_driver: orm
    firewall_name: main
    user_class: Kami\UserBundle\Entity\User
    service:
        mailer: fos_user.mailer.twig_swift
    from_email:
        address: "%mailer_user%"
        sender_name: "%mailer_user%"

# LexikJWTAuthentication Configuration
lexik_jwt_authentication:
    private_key_path: '%jwt_private_key_path%'
    public_key_path:  '%jwt_public_key_path%'
    pass_phrase:      '%jwt_key_pass_phrase%'
    token_ttl:        '%jwt_token_ttl%'

# NelmioCors Configuration
nelmio_cors:
    paths:
        '^/api':
            allow_origin: ['*']
            allow_headers: ['*']
            allow_methods: ['POST', 'PUT', 'GET', 'DELETE']
            max_age: 3600

# StofDoctrineExtensions Configuration
stof_doctrine_extensions:
    default_locale: en_US
    orm:
        default:
            tree: true
            timestampable: true

# VichUploaderBundle Configutration
vich_uploader:
    db_driver: orm

# KhepinYamlFixtures Configuration
khepin_yaml_fixtures:
    resources:
        - KamiUserBundle
        - KamiWorkerBundle
        - KamiContentBundle
    directory: Resources/fixtures

# LopiPusher Configuration
lopi_pusher:
    # Default configuration
    scheme: "%pusher_scheme%"
    host: "%pusher_host%"
    port: "%pusher_port%"
    cluster: "%pusher_cluster%"
    timeout: "%pusher_timeout%"
    debug: "%pusher_debug%"
    app_id: "%pusher_app_id%"
    key: "%pusher_key%"
    secret: "%pusher_secret%"

# Nelmio ApiDoc Configuration
nelmio_api_doc:
    areas:
        path_patterns:
            - ^/api(?!/doc$)

kami_ico_bench:
    private_key: ""
    public_key: ""
    guzzle_options: ~