imports:
    - { resource: config.yml }

doctrine:
    dbal:
        driver: pdo_pgsql
        url: "%env(DATABASE_URL)%"

snc_redis:
    clients:
        cache:
            type: predis
            alias: cache
            dsn: "%env(REDIS_URL)%"
            logging: false
        doctrine:
            metadata_cache:
                client: cache
                entity_manager: default
            result_cache:
                client: cache
                entity_manager: default
            query_cache:
                client: cache
                entity_manager: default
            second_level_cache:
                client: default
                entity_manager: default
monolog:
    handlers:
        main:
            type: fingers_crossed
            action_level: error
            handler: nested
        nested:
            type:  stream
            path:  "php://stderr"
            level: debug
        console:
            type: console
            process_psr_3_messages: false
