kami_api_core:
  locales: ['en', 'ru']
  resources:
    - name: post
      entity: Kami\ContentBundle\Entity\Post
      strategies:
          create: "kami.post_creation_strategy"
          update: "kami.post_update_strategy"

    - name: like
      entity: Kami\ContentBundle\Entity\Like
      strategies:
          create: "kami.like_creation_strategy"
          delete: "kami.like_delete_strategy"

    - name: tag
      entity: Kami\ContentBundle\Entity\Tag
      strategies:
           index: "kami.tag_index_strategy"

    - { name: asset, entity: Kami\AssetBundle\Entity\Asset }
    - { name: token, entity: Kami\AssetBundle\Entity\TradableToken}
    - { name: market-cap, entity: Kami\AssetBundle\Entity\MarketCap}
    - { name: token-type, entity: Kami\AssetBundle\Entity\TokenType}
    - { name: token-type-standard, entity: Kami\AssetBundle\Entity\TokenTypeStandard}
    - { name: volume, entity: Kami\AssetBundle\Entity\Volume}

    - { name: tag-group, entity: Kami\ContentBundle\Entity\TagGroup }

    - { name: filter-settings, entity: Kami\FilterBundle\Entity\FilterSettings }
    - { name: filter-item, entity: Kami\FilterBundle\Entity\FilterItem }

    - { name: consensus-type, entity: Kami\IcoBundle\Entity\ConsensusType }
    - { name: department, entity: Kami\IcoBundle\Entity\Department }
    - { name: dev-stages, entity: Kami\IcoBundle\Entity\DevStages }
    - { name: industry, entity: Kami\IcoBundle\Entity\Industry }
    - { name: mood-signal, entity: Kami\IcoBundle\Entity\MoodSignal}
    - { name: person, entity: Kami\IcoBundle\Entity\Person}
    - { name: sale-stage, entity: Kami\IcoBundle\Entity\SaleStage}
    - { name: ico, entity: Kami\IcoBundle\Entity\Ico }
    - { name: ico-values, entity: Kami\IcoBundle\Entity\IcoValues }
    - { name: dates, entity: Kami\IcoBundle\Entity\Dates }
    - { name: development, entity: Kami\IcoBundle\Entity\Development }
    - { name: finance, entity: Kami\IcoBundle\Entity\Finance }
    - { name: legal, entity: Kami\IcoBundle\Entity\Legal }
    - { name: social-media, entity: Kami\IcoBundle\Entity\SocialMedia }

    - { name: user, entity: Kami\UserBundle\Entity\User }

    - { name: worker, entity: Kami\WorkerBundle\Entity\Worker }
    - { name: web-feed, entity: Kami\WorkerBundle\Entity\WebFeed }
    - { name: facebook-feed, entity: Kami\WorkerBundle\Entity\FacebookFeed }
    - { name: twitter-feed, entity: Kami\WorkerBundle\Entity\TwitterFeed }
    - { name: reddit-feed, entity: Kami\WorkerBundle\Entity\RedditFeed }

    - name: log
      entity: Kami\WorkerBundle\Logger\Log
      strategies:
          index: "kami.logger.index_strategy"
          filter: "kami.logger.filter_strategy"
          create: "kami.logger.creation_strategy"
          update: "kami.common.not_found_strategy"
          delete: "kami.common.not_found_strategy"