kami_api_core:
  locales: ['en', 'ru']
  resources:
    - name: post
      entity: Kami\ContentBundle\Entity\Post
      strategies:
          create: "kami.post_creation_strategy"

    - { name: tag, entity: Kami\ContentBundle\Entity\Tag }
    - { name: worker, entity: Kami\WorkerBundle\Entity\Worker }
    - { name: web-feed, entity: Kami\WorkerBundle\Entity\WebFeed }
    - { name: facebook-feed, entity: Kami\WorkerBundle\Entity\FacebookFeed }
    - { name: twitter-feed, entity: Kami\WorkerBundle\Entity\TwitterFeed }
    - { name: reddit-feed, entity: Kami\WorkerBundle\Entity\RedditFeed }
    - { name: asset, entity: Kami\AssetBundle\Entity\Asset }
    - { name: filter-settings, entity: Kami\FilterBundle\Entity\FilterSettings }
    - { name: ico, entity: Kami\IcoBundle\Entity\Ico }

    - name: token
      entity: Kami\AssetBundle\Model\TradableToken
      strategies:
          index: "kami.token_screener.index_strategy"
          filter: "kami.token_screener.filter_strategy"
          create: "kami.common.not_found_strategy"
          update: "kami.common.not_found_strategy"
          delete: "kami.common.not_found_strategy"