kami_api_core:
  locales: ['en', 'ru']
  resources:
    - { name: website-post, entity: Kami\ContentBundle\Entity\WebsitePost }
    - { name: tag, entity: Kami\ContentBundle\Entity\Tag }
    - { name: worker, entity: Kami\WorkerBundle\Entity\Worker }