kami_worker:
    resource: "@KamiWorkerBundle/Controller/"
    type:     annotation
    prefix:   /

kami_api_core:
    resource: "@KamiApiCoreBundle/Resources/config/routing.yml"

api_login_check:
    path: /api/login_check