kami_api_core:
    resource: "@KamiApiCoreBundle/Resources/config/routing.yml"
    prefix:   /

api_login_check:
    path: /api/login_check

kami_frontend:
    resource: "@KamiFrontendBundle/Controller/"
    type:     annotation
    prefix:   /
