kami_worker:
    resource: "@KamiWorkerBundle/Controller/"
    type:     annotation
    prefix:   /

kami_content:
    resource: "@KamiContentBundle/Controller/"
    type:     annotation
    prefix:   /

kami_user:
    resource: "@KamiUserBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

gesdinet_jwt_refresh_token:
    path:     /api/token/refresh
    defaults: { _controller: gesdinet.jwtrefreshtoken:refresh }

kami_api_core:
    resource: "@KamiApiCoreBundle/Resources/config/routing.xml"

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }