kami_worker:
    resource: "@KamiWorkerBundle/Controller/"
    type:     annotation
    prefix:   /

kami_content:
    resource: "@KamiContentBundle/Controller/"
    type:     annotation
    prefix:   /

api_login_check:
    path: /api/login_check

kami_api_core:
    resource: "@KamiApiCoreBundle/Resources/config/routing.xml"

app.swagger_ui:
    path: /api/doc
    methods: GET
    defaults: { _controller: nelmio_api_doc.controller.swagger_ui }