security:
    encoders:
        FOS\UserBundle\Model\UserInterface: bcrypt

    providers:
        fos_userbundle:
            id: fos_user.user_provider.username_email
        kami_workerbundle:
            id: kami_worker.user_provider
        kami_socketserver:
            id: kami_worker.socket_user_provider
        chain_provider:
            chain:
                providers: [fos_userbundle, kami_workerbundle, kami_socketserver]

    firewalls:
        login:
            pattern:   ^/api/login
            stateless: true
            anonymous: true
            provider:  fos_userbundle
            form_login:
                check_path:               /api/login_check
                username_parameter:       username
                password_parameter:       password
                success_handler:          lexik_jwt_authentication.handler.authentication_success
                failure_handler:          lexik_jwt_authentication.handler.authentication_failure
                require_previous_session: false

        socket_server:
            pattern: ^/api/schedule
            stateless: true
            provider: kami_socketserver
            guard:
                authenticators:
                    - kami_worker.socket_server_authenticator

        api:
            pattern:   ^/api
            stateless: true
            anonymous: true
            provider: chain_provider
            guard:
                authenticators:
                    - lexik_jwt_authentication.jwt_token_authenticator
                    - kami_worker.authenticator
                entry_point: lexik_jwt_authentication.jwt_token_authenticator

        worker:
            pattern:   ^/worker/heartbeat
            stateless: true
            provider: kami_workerbundle
            guard:
                authenticators:
                    - kami_worker.authenticator


    access_control:
        - { path: ^/api/login, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/worker/authenticate, roles: IS_AUTHENTICATED_ANONYMOUSLY }
        - { path: ^/api/schedule, roles: ROLE_SOCKET_SERVER }