<?php

namespace Kami\UserBundle\Repository;

/**
 * UserRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class UserRepository extends \Doctrine\ORM\EntityRepository
{
    public function findOneByWorkerToken($workerToken)
    {
        return $this->createQueryBuilder('u')
            ->where('u.workerToken = :workerToken')
            ->setParameter('workerToken', $workerToken)
            ->getQuery()
            ->getOneOrNullResult();
    }
}
