<?php

namespace Kami\AssetBundle\Repository;

/**
 * AlgorithmRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AlgorithmRepository extends \Doctrine\ORM\EntityRepository
{
}
