<?php

namespace Kami\AssetBundle\Repository;

/**
 * PairRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class PairRepository extends \Doctrine\ORM\EntityRepository
{
}
