<?php

namespace Kami\AssetBundle\Repository;

/**
 * TokenTypeStandartRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TokenTypeStandardRepository extends \Doctrine\ORM\EntityRepository
{
}
