<?php

namespace Kami\AssetBundle\Repository;

/**
 * TokenTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TradableTokenRepository extends \Doctrine\ORM\EntityRepository
{
}
