<?php

namespace Kami\WorkerBundle\Repository;

/**
 * FacebookFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
