<?php
/**
 * Created by PhpStorm.
 * User: vadim
 * Date: 04.04.18
 * Time: 13:09
 */

namespace Kami\WorkerBundle\Repository;

/**
 * RedditFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedditFeedRepository extends \Doctrine\ORM\EntityRepository
{
}