<?php

namespace Kami\WorkerBundle\Repository;

/**
 * RedditFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class RedditFeedRepository extends \Doctrine\ORM\EntityRepository
{
}