<?php

namespace Kami\WorkerBundle\Repository;

/**
 * TwitterFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
