<?php

namespace Kami\WorkerBundle\Repository;

/**
 * WebFeedRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebFeedRepository extends \Doctrine\ORM\EntityRepository
{
}
