parameters:
    kami_worker.user_provider.class:               Kami\WorkerBundle\Security\WorkerUserProvider
    kami_worker.authenticator.class:               Kami\WorkerBundle\Security\WorkerAuthenticator
    kami_worker.socket_user_provider.class:        Kami\WorkerBundle\Security\SocketServerUserProvider
    kami_worker.socket_server_authenticator.class: Kami\WorkerBundle\Security\SocketServerAuthenticator
    kami_worker.scheduler.class:                   Kami\WorkerBundle\Scheduler\Scheduler
    kami_worker.post_creation_listener.class:      Kami\WorkerBundle\Listener\PostCreationListener

services:
    kami_worker.user_provider:
        class: "%kami_worker.user_provider.class%"
        arguments:
            - "@doctrine"

    kami_worker.socket_user_provider:
        class: "%kami_worker.socket_user_provider.class%"

    kami_worker.authenticator:
        class: "%kami_worker.authenticator.class%"
        arguments:
            - "@kami_worker.user_provider"

    kami_worker.socket_server_authenticator:
        class: "%kami_worker.socket_server_authenticator.class%"
        arguments:
            - "%socket_server_secret%"

    kami_worker.scheduler:
         class: "%kami_worker.scheduler.class%"
         arguments:
             - "@doctrine"
         public: true

    kami_worker.post_creation_listener:
         class: "%kami_worker.post_creation_listener.class%"
         tags:
             - { name: kernel.event_listener, event: kami.api_core.resource_create }