parameters:
    kami_worker.user_provider.class: Kami\WorkerBundle\Security\WorkerUserProvider
    kami_worker.authenticator.class: Kami\WorkerBundle\Security\WorkerAuthenticator

services:
    kami_worker.user_provider:
        class: "%kami_worker.user_provider.class%"
        arguments:
            - "@doctrine"

    kami_worker.authenticator:
        class: "%kami_worker.authenticator.class%"
        arguments:
            - "@kami_worker.user_provider"