<?php

namespace Kami\ContentBundle\Repository;

/**
 * FacebookPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FacebookPostRepository extends \Doctrine\ORM\EntityRepository
{
}
