<?php

namespace Kami\ContentBundle\Repository;

/**
 * PostTagRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagAddedByRepository extends \Doctrine\ORM\EntityRepository
{
}
