<?php


namespace Kami\ContentBundle\Repository;

/**
 * TagGroupRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagGroupRepository extends \Doctrine\ORM\EntityRepository
{
}