<?php

namespace Kami\ContentBundle\Repository;

/**
 * TagPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TagPostRepository extends \Doctrine\ORM\EntityRepository
{
}
