<?php

namespace Kami\ContentBundle\Repository;

/**
 * TwitterPostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TwitterPostRepository extends \Doctrine\ORM\EntityRepository
{
}
