<?php

namespace Kami\ContentBundle\Repository;

/**
 * WebsitePostRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class WebsitePostRepository extends \Doctrine\ORM\EntityRepository
{
}
