parameters:
    kami.ico_normalizer.abstract.class: Kami\IcoBundle\Normalizer\AbstractIcoNormalizer
    kami.ico_index_strategy:
        - get_reflection_from_request
        - validate_resource_access
        - get_query_builder
        - build_select_query
        - sort_ico
        - paginate
        - build_serializer
        - serialize
    kami.ico_filter_strategy:
        - get_reflection_from_request
        - validate_resource_access
        - validate_filters
        - get_query_builder
        - build_select_query
        - filter_ico
        - sort_ico
        - paginate
        - build_serializer
        - serialize

services:

    kami.request_processor.sort_ico.step:
        class: Kami\IcoBundle\RequestProcessor\IcoSortStep
        arguments:
            - "@kami.api_core.access_manager"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "sort_ico" }

    kami.request_processor.filter_ico.step:
        class: Kami\IcoBundle\RequestProcessor\IcoFilterStep
        arguments:
            - "@kami.api_core.access_manager"
        tags:
            - { name: "kami_api_core.strategy_step", shortcut: "filter_ico" }

    kami.sync_icos.command:
        class: Kami\IcoBundle\Command\SyncIcosCommand
        arguments:
            - "@kami.icobench.client"
            - "@kami.ico_normalizer.icobench"
            - "@doctrine.orm.entity_manager"
            - "@logger"
        tags:
            - { name: 'console.command' }

    kami.ico_normalizer.abstract:
        class: "%kami.ico_normalizer.abstract.class%"
        abstract: true
        arguments:
            - "@doctrine.orm.entity_manager"

    kami.ico_property_normalizer.abstract:
          class: "%kami.ico_normalizer.abstract.class%"
          abstract: true
          arguments:
              - "@doctrine.orm.entity_manager"

    kami.ico_normalizer.icobench:
        class: Kami\IcoBundle\Normalizer\IcoBench\IcoBenchNormalizer
        arguments:
            - "@doctrine.orm.entity_manager"
            -
              - "@kami.ico_property_normalizer.icobench.scalar"
              - "@kami.ico_property_normalizer.icobench.team"
              - "@kami.ico_property_normalizer.icobench.restrictions"
              - "@kami.ico_property_normalizer.icobench.industries"
              - "@kami.ico_property_normalizer.icobench.asset"
              - "@kami.ico_property_normalizer.icobench.country"
              - "@kami.ico_property_normalizer.icobench.finance"
              - "@kami.ico_property_normalizer.icobench.dates"

    kami.ico_property_normalizer.icobench.scalar:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\ScalarNormalizer

    kami.ico_property_normalizer.icobench.asset:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\AssetNormalizer
        parent: "kami.ico_property_normalizer.abstract"

    kami.ico_property_normalizer.icobench.team:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\TeamNormalizer
        parent: "kami.ico_property_normalizer.abstract"

    kami.ico_property_normalizer.icobench.restrictions:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\RestrictedCountriesNormalizer
        parent: "kami.ico_property_normalizer.abstract"

    kami.ico_property_normalizer.icobench.industries:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\IndustryNormalizer
        parent: "kami.ico_property_normalizer.abstract"

    kami.ico_property_normalizer.icobench.country:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\CountryNormalizer
        parent: "kami.ico_property_normalizer.abstract"

    kami.ico_property_normalizer.icobench.finance:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\FinanceNormalizer
        arguments:
            - "@doctrine.orm.entity_manager"

    kami.ico_property_normalizer.icobench.dates:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\DatesNormalizer
        arguments:
            - "@doctrine.orm.entity_manager"
