parameters:
    kami.ico_normalizer.abstract.class: Kami\IcoBundle\Normalizer\AbstractIcoNormalizer

services:

    kami.sync_icos.command:
        class: Kami\IcoBundle\Command\SyncIcosCommand
        arguments:
            - "@kami.icobench.client"
            - "@kami.ico_normalizer.icobench"
            - "@doctrine.orm.entity_manager"
            - "@logger"
        tags:
            - { name: 'console.command' }

    kami.ico_normalizer.abstract:
        class: "%kami.ico_normalizer.abstract.class%"
        abstract: true
        arguments:
            - "@doctrine.orm.entity_manager"

    kami.ico_normalizer.icobench:
        class: Kami\IcoBundle\Normalizer\IcoBench\IcoBenchNormalizer
        arguments:
            - "@doctrine.orm.entity_manager"
            - ["@kami.ico_normalizer.icobench.scalar", "@kami.ico_normalizer.icobench.team", "@kami.ico_normalizer.icobench.restrictions",
              "@kami.ico_normalizer.icobench.kyc", "@kami.ico_normalizer.icobench.advisors", "@kami.ico_normalizer.icobench.industries",
                "@kami.ico_normalizer.icobench.asset", "@kami.ico_normalizer.icobench.country"]
#                - "@kami.ico_normalizer.icobench.kyc"
#                -
#                - "@kami.ico_normalizer.icobench.team_members"
#                -
    kami.ico_normalizer.icobench.scalar:
        class: Kami\IcoBundle\Normalizer\IcoBench\Property\ScalarNormalizer

    kami.ico_normalizer.icobench.asset:
        class: Kami\IcoBundle\Normalizer\IcoBench\AssetNormalizer
        parent: "kami.ico_normalizer.abstract"

    kami.ico_normalizer.icobench.team:
        class: Kami\IcoBundle\Normalizer\IcoBench\TeamNormalizer
        parent: "kami.ico_normalizer.abstract"

    kami.ico_normalizer.icobench.restrictions:
            class: Kami\IcoBundle\Normalizer\IcoBench\RestrictedCountriesNormalizer
            parent: "kami.ico_normalizer.abstract"

    kami.ico_normalizer.icobench.kyc:
                class: Kami\IcoBundle\Normalizer\IcoBench\KycNormalizer
                parent: "kami.ico_normalizer.abstract"

    kami.ico_normalizer.icobench.advisors:
                    class: Kami\IcoBundle\Normalizer\IcoBench\AdvisorsNormalizer
                    parent: "kami.ico_normalizer.abstract"

    kami.ico_normalizer.icobench.industries:
                        class: Kami\IcoBundle\Normalizer\IcoBench\IndustryNormalizer
                        parent: "kami.ico_normalizer.abstract"

    kami.ico_normalizer.icobench.country:
                            class: Kami\IcoBundle\Normalizer\IcoBench\IcoCountryNormalizer
                            parent: "kami.ico_normalizer.abstract"


