<?php

namespace Kami\IcoBundle\Repository;

/**
 * AcceptedCurrencyRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class AcceptedCurrencyRepository extends \Doctrine\ORM\EntityRepository
{
}
