<?php

namespace Kami\IcoBundle\Repository;

/**
 * BlockchainAdvisorRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class BlockchainAdvisorRepository extends \Doctrine\ORM\EntityRepository
{
}
