<?php

namespace Kami\IcoBundle\Repository;

/**
 * ConsensusTypeRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ConsensusTypeRepository extends \Doctrine\ORM\EntityRepository
{
}
