<?php

namespace Kami\IcoBundle\Repository;

/**
 * CountryRestrictionRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class CountryRestrictionRepository extends \Doctrine\ORM\EntityRepository
{
}
