<?php

namespace Kami\IcoBundle\Repository;

/**
 * DevelopmentStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevelopmentStageRepository extends \Doctrine\ORM\EntityRepository
{
}
