<?php

namespace Kami\IcoBundle\Repository;

/**
 * DevelopmentRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevelopmentRepository extends \Doctrine\ORM\EntityRepository
{
}
