<?php

namespace Kami\IcoBundle\Repository;

/**
 * DevStagesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class DevStagesRepository extends \Doctrine\ORM\EntityRepository
{
}
