<?php

namespace Kami\IcoBundle\Repository;

/**
 * FinanceRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class FinanceRepository extends \Doctrine\ORM\EntityRepository
{
}
