<?php

namespace Kami\IcoBundle\Repository;

use Doctrine\ORM\EntityRepository;

/**
 * IcoRepository
 *
 * This class was generated by the PhpStorm "Php Annotations" Plugin. Add your own custom
 * repository methods below.
 */
class IcoRepository extends EntityRepository
{
}
