<?php

namespace Kami\IcoBundle\Repository;

/**
 * IcoValuesRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class IcoValuesRepository extends \Doctrine\ORM\EntityRepository
{
}
