<?php

namespace Kami\IcoBundle\Repository;

/**
* IndustryAdvisorRepository
*
 * This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
 */
class IndustryAdvisorRepository extends \Doctrine\ORM\EntityRepository
{
}