<?php


namespace Kami\IcoBundle\Repository;

/**
 * IndustryRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class KycRepository extends \Doctrine\ORM\EntityRepository
{
}