<?php

namespace Kami\IcoBundle\Repository;

/**
 * LegalPartnerRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LegalPartnerRepository extends \Doctrine\ORM\EntityRepository
{
}
