<?php

namespace Kami\IcoBundle\Repository;

/**
 * SocialMediaLinksRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class LinksRepository extends \Doctrine\ORM\EntityRepository
{
}
