<?php

namespace Kami\IcoBundle\Repository;

/**
 * MoodSignalRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class MoodSignalRepository extends \Doctrine\ORM\EntityRepository
{
}
