<?php

namespace Kami\IcoBundle\Repository;

/**
 * SaleStageRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class SaleStageRepository extends \Doctrine\ORM\EntityRepository
{
}
