<?php


namespace Kami\IcoBundle\Repository;


/**
* TokenTypeRepository
*
 * This class was generated by the Doctrine ORM. Add your own custom
* repository methods below.
 */
class TokenTypeRepository extends \Doctrine\ORM\EntityRepository
{

}