parameters:
    kami_api_core.routing_loader.class: Kami\ApiCoreBundle\Routing\ApiLoader
    kami_api_core.api_manager.class:    Kami\ApiCoreBundle\Manager\ApiManager
    kami_api_core.access_manager.class: Kami\ApiCoreBundle\Security\AccessManager
    kami_api_core.form_factory.class:   Kami\ApiCoreBundle\Form\Factory

services:
    kami_api_core.routing_loader:
        class: "%kami_api_core.routing_loader.class%"
        arguments:
          - "%kami_api_core.resources%"
          - "%kami_api_core.locales%"
          - "%kernel.default_locale%"
        tags: [ routing.loader ]

    kami_api_core.access_manager:
        class: "%kami_api_core.access_manager.class%"
        arguments:
          - "@security.token_storage"
          - "@annotation_reader"

    kami_api_core.form_factory:
        class: "%kami_api_core.form_factory.class%"
        arguments:
          - "@form.factory"
          - "@annotation_reader"

    kami_api_core.api_manager:
        class: "%kami_api_core.api_manager.class%"
        arguments:
          - "@doctrine"
          - "@kami_api_core.access_manager"
          - "@kami_api_core.form_factory"
          - "@jms_serializer"
          - "%kami_api_core.pagination.per_page%"

