<?php
/**
 * Created by PhpStorm.
 * User: roman
 * Date: 26.03.18
 * Time: 11:08
 */

namespace Kami\ApiCoreBundle\Resources\Fixtures\Repository;

/**
 * TestRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class TestRepository extends \Doctrine\ORM\EntityRepository
{

}